# Generated by Django 5.1.15 on 2026-03-09 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(choices=[(1, 'Étage 1'), (2, 'Étage 2'), (3, 'Étage 3')], verbose_name='Étage')),
                ('column', models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='Colonne (A-E)')),
                ('row', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Ligne (1-6)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('fertile', 'Fertile'), ('clear', 'Clair (infertile)'), ('dead_embryo', 'Mort embryonnaire'), ('cracked', 'Fissuré'), ('hatched', 'Éclos ✓'), ('failed', 'Échoué'), ('removed', 'Retiré')], default='pending', max_length=20, verbose_name='Statut')),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids initial (g)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Œuf',
                'verbose_name_plural': 'Œufs',
                'ordering': ['floor', 'column', 'row'],
            },
        ),
        migrations.CreateModel(
            name='IncubationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du lot')),
                ('species', models.CharField(choices=[('chicken', 'Poulet (21j)'), ('duck', 'Canard (28j)'), ('quail', 'Caille (17j)'), ('turkey', 'Dinde (28j)'), ('goose', 'Oie (30j)'), ('pheasant', 'Faisan (24j)'), ('other', 'Autre')], default='chicken', max_length=20, verbose_name='Espèce')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Race / Souche')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Provenance des œufs')),
                ('entry_date', models.DateField(verbose_name="Date d'entrée en couveuse")),
                ('status', models.CharField(choices=[('active', 'En cours'), ('lockdown', 'Lockdown (J18)'), ('hatching', 'Éclosion en cours'), ('completed', 'Terminé'), ('aborted', 'Abandonné')], default='active', max_length=20, verbose_name='Statut')),
                ('total_eggs', models.PositiveIntegerField(verbose_name="Nombre total d'œufs")),
                ('target_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température cible (°C)')),
                ('target_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humidité cible (%)')),
                ('hatched_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Œufs éclos')),
                ('failed_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Œufs échoués')),
                ('actual_hatch_date', models.DateField(blank=True, null=True, verbose_name="Date réelle d'éclosion")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Lot d'incubation",
                'verbose_name_plural': "Lots d'incubation",
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='EggObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candling_number', models.PositiveSmallIntegerField(choices=[(0, 'Observation libre'), (1, 'Mirage 1 (J7)'), (2, 'Mirage 2 (J14)'), (3, 'Mirage 3 (J18)')], default=0, verbose_name='Mirage')),
                ('result', models.CharField(choices=[('fertile', 'Fertile / Vivant'), ('clear', 'Clair (infertile)'), ('dead', 'Mort embryonnaire'), ('uncertain', 'Incertain'), ('ready', 'Prêt pour éclosion')], max_length=20, verbose_name='Résultat')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('observed_by', models.CharField(blank=True, max_length=100, verbose_name='Observé par')),
                ('egg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='incubation.egg', verbose_name='Œuf')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.AddField(
            model_name='egg',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eggs', to='incubation.incubationbatch', verbose_name='Lot'),
        ),
        migrations.CreateModel(
            name='IncubatorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/Heure')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température (°C)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humidité (%)')),
                ('co2_ppm', models.PositiveIntegerField(blank=True, null=True, verbose_name='CO2 (ppm)')),
                ('event', models.CharField(blank=True, max_length=200, verbose_name='Événement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='incubation.incubationbatch', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Log couveuse',
                'verbose_name_plural': 'Logs couveuse',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='egg',
            unique_together={('batch', 'floor', 'column', 'row')},
        ),
    ]
