# Generated by Django 5.1.15 on 2026-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egg',
            options={'ordering': ['identifier'], 'verbose_name': 'Œuf', 'verbose_name_plural': 'Œufs'},
        ),
        migrations.AddField(
            model_name='egg',
            name='identifier',
            field=models.CharField(default=1, editable=False, max_length=10, verbose_name="N° sur l'œuf"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='egg',
            name='column',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='Colonne'),
        ),
        migrations.AlterField(
            model_name='egg',
            name='row',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Ligne'),
        ),
    ]
